llama-2-70b-chat-hf:
  prompt_template: "llama-2-70b-chat-hf/prompt.txt"
  fn_completions: "vllm_local_completions"
  completions_kwargs:
    model_name: "meta-llama/Llama-2-70b-chat-hf"
    max_new_tokens: 50
    temperature: 0
  model_kwargs:
    dtype: "bfloat16"
    enable_chunked_prefill: True
  completion_parser_kwargs:
    outputs_to_match:
      1: '(?i)output \(a\)'
      2: '(?i)output \(b\)'