llama-2-70b-chat-hf:
  prompt_template: "Meta-Llama-3-70B-Instruct/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "meta-llama/Llama-2-70b-chat-hf"
    max_new_tokens: 50
    temperature: 0
  completion_parser_kwargs:
    outputs_to_match:
      1: '(?i)output \(a\)'
      2: '(?i)output \(b\)'